### ISSUE TITLE
Trouble with serialConfig.cmake

### ISSUE THREAD

**Issue by millyajr** [MirkoFerrati/irobotcreate2ros#5]
![image](https://cloud.githubusercontent.com/assets/16889920/12569786/fb79ab44-c39f-11e5-9f65-6854c9a5a988.png)

The following error does not allow me to run catkin_make successfully. I have both ROS Serial, and ROS joy. Any help is greatly appreciated.

**Comment by MirkoFerrati** [comment]
Hi,
please note the difference between
http://wiki.ros.org/serial
and 
http://wiki.ros.org/rosserial

The first one is a wrapper around a simple serial communication library, while the second one is a big package with lot of stuff for using ROS on embedded systems such as Arduinos.
We need the first one, install with sudo apt-get install ros-indigo-serial
Let me know if it solves the error!

**Comment by millyajr** [comment]
I will try today, thank you for the speedy reply, you may be saving my senior year!

Jake Millyard
BSEE '16
517-759-2707tel:517-759-2707

On Tue, Jan 26, 2016 at 3:05 AM -0800, "Mirko Ferrati" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,
please note the difference between
http://wiki.ros.org/serial
and
http://wiki.ros.org/rosserial

The first one is a wrapper around a simple serial communication library, while the second one is a big package with lot of stuff for using ROS on embedded systems such as Arduinos.
We need the first one, install with sudo apt-get install ros-indigo-serial
Let me know if it solves the error!

##

**Comment by millyajr** [comment]
I now run into the issue that

[rosrun] Couldn't find executable named irobotcreate2 below /home/mario/catkin_ws/install/share/irobotcreate2
[rosrun] Found the following, but they're either not files,
[rosrun] or not executable:
[rosrun]   /home/mario/catkin_ws/install/share/irobotcreate2

I have tried to execute it throughout the home all the way through to the src directory and no luck? Although i am fairly new to ROS i am pretty familar with the concept to its operation so any help is appreciated.

**Comment by MirkoFerrati** [comment]
Hi, this seems to be a different problem, can you check if there is an executable inside /home/mario/catkin_ws/devel/lib/irobotcreate2/
?

you should find these ones:
basic_commands  irobotcreate2  irobotcreate2_lightweight  joy_node  keyboard_node

**Comment by millyajr** [comment]
[cid:9192154c-84c4-40a3-932e-c400a8f56daa]
These are the files that appear in the directory.

**Comment by MirkoFerrati** [comment]
I can't see the list of files, just a hash, can you try to answer directly from github? I assume you wanted to post a picture

**Comment by millyajr** [comment]
Yes let me hop on there

Jake Millyard
BSEE '16
517-759-2707tel:517-759-2707

On Wed, Jan 27, 2016 at 10:44 AM -0800, "Mirko Ferrati" <notifications@github.com<mailto:notifications@github.com>> wrote:

I can't see the list of files, just a hash, can you try to answer directly from github? I assume you wanted to post a picture

##

**Comment by millyajr** [comment]
![image](https://cloud.githubusercontent.com/assets/16889920/12624290/49c7b734-c4fc-11e5-840c-95865780ecef.png)

Let me know if you can see this,

**Comment by MirkoFerrati** [comment]
Yes, those are the executables, ros should find them in that folder.
You can even try to run them directly from the shell, they should give error but still provide some output.
Can you do the standard ROS checks, source devel/setup.bash, rospack profile, and see if something changes?

**Comment by millyajr** [comment]
is there some type of sourcing i should i put in additional to my bashrc? 
![image](https://cloud.githubusercontent.com/assets/16889920/12624531/943f2760-c4fd-11e5-81e6-276a4a1227ca.png)

![image](https://cloud.githubusercontent.com/assets/16889920/12624539/9da920b2-c4fd-11e5-9e2c-e2a7658e07b3.png)
and this what i get from attempting a launch from that shell

**Comment by MirkoFerrati** [comment]
Everything looks good except for ~/catkin_ws/install/setup.bash
I don't have it in my configuration. It may be the problem, can you try to comment it out?

**Comment by millyajr** [comment]
do you know why it is looking for the executable in this path "[rosrun] Couldn't find executable named irobotcreate2 below /home/mario/catkin_ws/install/share/irobotcreate2"

**Comment by MirkoFerrati** [comment]
No, no idea :(
The only option I see is to remove the install/setup.bash line inside bashrc

**Comment by millyajr** [comment]
![image](https://cloud.githubusercontent.com/assets/16889920/12624902/5cd11796-c4ff-11e5-8ffe-33a5e185df9d.png)

is this good?!

**Comment by MirkoFerrati** [comment]
Yes!!
Now it works :)

**Comment by millyajr** [comment]
thank you so very much, you have written great software

**Comment by MirkoFerrati** [comment]
You are welcome, feel free to open issues for feature or other problems!
