### ISSUE TITLE
[joy-1] process has died

### ISSUE THREAD

**Issue by joeldriver** [MirkoFerrati/irobotcreate2ros#6]
Hello-

I am using Ubuntu 14.04 fully patched and I have installed and configured ros-indigo as documented in the tutorials on ros.org.  I have the same versions/config on a 64bit and 32bit computer and have the same issue.  I have included the logs from both 

`roslaunch irobotcreate2 irobotcreate2.launch`
 and 
`roslaunch irobotcreate2 irobot_joy.launch`

I have tested with a very old Logitech gamepad and a wired xbox360 controller.  These logs are from the xbox360 controller.  I have tested other joy packages and looked at the output with "rostopic echo" and everything seems to work but I am new to ROS and may be missing something obvious.

This is the terminal output for irobot_joy.launch:

```
joel@joel-xps:~/catkin_ws$ roslaunch irobotcreate2 irobot_joy.launch

... logging to /home/joel/.ros/log/d6276670-c84e-11e5-bd35-bc77370aba1d/roslaunch-joel-xps-14873.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://joel-xps:37218/

SUMMARY
========

PARAMETERS
 * /joy_driver/dev: /dev/input/js0
 * /rosdistro: indigo
 * /rosversion: 1.11.16

NODES
  /
    joy (irobotcreate2/joy_node)
    joy_driver (joy/joy_node)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[joy-1]: started with pid [14891]
process[joy_driver-2]: started with pid [14892]
[ INFO] [1454267679.489605717]: Joy Handler Started
[ INFO] [1454267679.509421361]: Opened joystick: /dev/input/js0. deadzone_: 0.050000.
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check
[joy-1] process has died [pid 14891, exit code -6, cmd /home/joel/catkin_ws/devel/lib/irobotcreate2/joy_node __name:=joy __log:=/home/joel/.ros/log/d6276670-c84e-11e5-bd35-bc77370aba1d/joy-1.log].
log file: /home/joel/.ros/log/d6276670-c84e-11e5-bd35-bc77370aba1d/joy-1*.log
^C[joy_driver-2] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
joel@joel-xps:~/catkin_ws$ 
```

Thanks-
Joel

[ros.logs.zip](https://github.com/MirkoFerrati/irobotcreate2ros/files/111469/ros.logs.zip)

**Comment by MirkoFerrati** [comment]
Hi, this doesn't look like a problem of irobotcreate2ros, but in order to be sure, can you try this?
http://wiki.ros.org/teleop_twist_joy

You should be able to use the joystick to move a turtle inside turtlesim. This way you will confirm that the error is not related to ros-joy.
Let me know if you managed to use the joystick in the turtlesim example and we will investigate more.

**Comment by joeldriver** [comment]
Hello-

When I run  `roslaunch teleop_twist_joy teleop.launch`  I can see the linear and angular data change via `rostopic echo /cmd_vel` but when I run `rosrun turtlesim turtlesim_node` the turtle does not move.  When I look at the topics via rqt_graph I see no arrow between teleop_twist_joy and turtlesim.  It looks like teleop_twist_joy is publishing to /cmd_vel and turtlesim is subscribing to /**turtle1**/cmd_vel and I am unclear on how to connect them.

Thanks-
Joel

**Comment by MirkoFerrati** [comment]
Topic remapping is easy in ROS, read this tutorial to learn how to do it
http://wiki.ros.org/Remapping%20Arguments

Anyway, can you post here a rostopic echo /joy ? There may be a bug related to missing buttons. Please press everything you have on your joystick while you do rostopic echo /joy .

**Comment by joeldriver** [comment]
I had been reading about roslaunch and never saw anything about remapping.  I wish I had typed that in Google a few days back.  Thank you  for pointing out what now seems obvious.

With my new remapping skill I was able to drive the turtlesim and the iRobot create2 via teleop_twist_joy.  I have pushed every button including the buttons in the analog sticks and the back, start and the big xbox button.  I have also moved every analog control and am unable to crash teleop_twist_joy.

So you can see the number of buttons reported by teleop_twist_joy here is the output of rostopic echo /joy:

```
---
header: 
  seq: 1505
  stamp: 
    secs: 1454466027
    nsecs: 303571870
  frame_id: ''
axes: [-0.0, -0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0]
buttons: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
---
```

While using the controller and watching the output I can account for every button and all but the last two axes that I assume some other controllers have.  I did the test with a wired xbox 360 controller.

I will do more testing and data collection if needed.

Thanks-
Joel

**Comment by MirkoFerrati** [comment]
Hi Joel,
Thanks for the debugging, we do have a problem in our code: PS3 joystick has more buttons and we use one of those for an optional functionality.
We will create a branch without that functionality, so that the number of buttons of your joystick will be sufficient.
At the moment, I prefer avoiding a run-time check for the size of the button array in the message, in the long run I will probably add an optional configuration parameter with the number of buttons of the joystick.
I will write here when the branch is ready. Meanwhile, you can comment out from here
https://github.com/MirkoFerrati/irobotcreate2ros/blob/master/src/joy_node.cpp#L101

to here 
https://github.com/MirkoFerrati/irobotcreate2ros/blob/master/src/joy_node.cpp#L125

and everything should work. Let me know!

**Comment by joeldriver** [comment]
Mirko-

That worked great!   

Looking in joy_node.h it is now easy to see you were using a PS3 controller.

Now that understand ROS a bit better...  Why did you include joystick functionality and not just depend on something like teleop_twist_joy for joystick control?  I guess I am curious if it is a technical reason or just personal preference...

Thank you for your help!
-Joel

**Comment by MirkoFerrati** [comment]
I will answer just for future references, sorry for the delay.
We wanted to have more control on the features provided by the irobotCreate, including the ability to make sounds and/or to control the speed with a different approach than the teleop_twist_joy.
Given the simple code of a teleop node, we decided to create our own copy.
The joy_node is not part of the core of the package anyway.
