### ISSUE TITLE
In file included from /home/mario/catkin_ws/src/irobotcreate2ros/src/irobotcreate2/OpenInterface.cpp:50:0: /home/mario/catkin_ws/src/irobotcreate2ros/src/irobotcreate2/../../include/irobotcreate2/OpenInterface.h:41:27: fatal error: serial/serial.h: No such file or directory  #include <serial/serial.h>                            ^

### ISSUE THREAD

**Issue by millyajr** [MirkoFerrati/irobotcreate2ros#8]
both "serial" and "joystick drivers" have been installed and built in the catkin_ws. advice?

**Comment by MirkoFerrati** [comment]
Hi, the issue may be related to line 54 of CmakeLists.txt

https://github.com/MirkoFerrati/irobotcreate2ros/blob/master/CMakeLists.txt#L54

can you try to change that line with 

include_directories(include ${catkin_INCLUDE_DIRS})

and see if the error persists?

**Comment by millyajr** [comment]
worked perfectly, thank you very much

**Comment by lucbettaieb** [comment]
Just had the same issue.  @MirkoFerrati you may want to change this in your CMakeLists.txt on master.

**Comment by MirkoFerrati** [comment]
Done
