### ISSUE TITLE
SAFE on LED and Dirt Detect light on.

### ISSUE THREAD

**Issue by singularitydefined** [MirkoFerrati/irobotcreate2ros#9]
Irobot Create 2 turns on but after launching displays SAFE on LED on Irobot and dirt detect light is on. Not sure how to control from here.. Any help would be appreciated.

laptop@laptop:~$ cd /home/laptop/irobotcreate2ros/model 
## laptop@laptop:~/irobotcreate2ros/model$ source generate_model.sh

Generating URDF...
xacro: Traditional processing is deprecated. Switch to --inorder processing!
To check for compatibility of your document, use option --check-order.
For more infos, see http://wiki.ros.org/xacro#Processing_Order
inconsistent namespace redefinitions for xmlns:xacro:
 old: http://www.ros.org/wiki/xacro
 new: http://ros.org/wiki/xacro (/home/laptop/catkin_ws/src/irobotcreate2ros-master/gazebo/axis.gazebo.xacro)
inconsistent namespace redefinitions for xmlns:xacro:
 old: http://www.ros.org/wiki/xacro
 new: http://ros.org/wiki/xacro (/home/laptop/catkin_ws/src/irobotcreate2ros-master/gazebo/wheel.gazebo.xacro)
inconsistent namespace redefinitions for xmlns:xacro:
 old: http://www.ros.org/wiki/xacro
 new: http://ros.org/wiki/xacro (/home/laptop/catkin_ws/src/irobotcreate2ros-master/gazebo/iRobot.gazebo.xacro)
redefining global property: pi
when processing file: iRobot.urdf.xacro
redefining global property: pi
when processing file: iRobot.urdf.xacro
redefining global property: pi
when processing file: iRobot.urdf.xacro
redefining global property: pi
when processing file: iRobot.urdf.xacro
redefining global property: pi
when processing file: iRobot.urdf.xacro
unsupported operand type(s) for ^: 'float' and 'float' 
when evaluating expression '1/12_10_3_0.17^2+1/12_5_3_0.08^2'
when processing file: iRobot.urdf.xacro
## Generating SDF...

laptop@laptop:~/irobotcreate2ros/model$ source /usr/share/gazebo/setup.sh
laptop@laptop:~/irobotcreate2ros/model$ export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:$(rospack find irobotcreate2)
laptop@laptop:~/irobotcreate2ros/model$ export GAZEBO_RESOURCE_PATH=$GAZEBO_RESOURCE_PATH:$(rospack find irobotcreate2)
laptop@laptop:~/irobotcreate2ros/model$ rosrun irobotcreate2 irobotcreate2
[ INFO] [1466229280.090790042]: Roomba for ROS 2.01
[ INFO] [1466229280.224081971]: Connected to Roomba.
[ INFO] [1466229280.324787791]: Waiting for roomba sensors
Sending OPCode: �
Sending OPCode: �
Sending OPCode: �
Sending OPCode: �

**Comment by MirkoFerrati** [comment]
Everything is fine, the application is up and running, waiting for commands.
You need an external program that controls the robot.
Try to launch any ros application that outputs a /cmd_vel topic
Some examples are :
https://github.com/ros-teleop
http://wiki.ros.org/stdr_simulator/Tutorials/Teleop%20with%20teleop_twist_keyboard
The robot should move.

**Comment by singularitydefined** [comment]
CMake Error at irobotcreate2ros/CMakeLists.txt:62 (add_executable):
  add_executable cannot create target "joy_node" because another target with
  the same name already exists.  The existing target is an executable created
  in source directory "/home/baxter/catkin_ws/src/joystick_drivers/joy".  See
  documentation for policy CMP0002 for more details.

CMake Error at irobotcreate2ros/CMakeLists.txt:76 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/libroslib.so" to target
  "joy_node" which is not built in this directory.

CMake Error at irobotcreate2ros/CMakeLists.txt:76 (target_link_libraries):
  Attempt to add link library "serial" to target "joy_node" which is not
  built in this directory.

CMake Error at irobotcreate2ros/CMakeLists.txt:76 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/libtf.so" to target
  "joy_node" which is not built in this directory.

CMake Error at irobotcreate2ros/CMakeLists.txt:76 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/libtf2_ros.so" to target
  "joy_node" which is not built in this directory.

CMake Error at irobotcreate2ros/CMakeLists.txt:76 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/libactionlib.so" to target
  "joy_node" which is not built in this directory.

CMake Error at irobotcreate2ros/CMakeLists.txt:76 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/libmessage_filters.so" to
  target "joy_node" which is not built in this directory.

CMake Error at irobotcreate2ros/CMakeLists.txt:76 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/libroscpp.so" to target
  "joy_node" which is not built in this directory.

CMake Error at irobotcreate2ros/CMakeLists.txt:76 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libboost_signals.so"
  to target "joy_node" which is not built in this directory.

CMake Error at irobotcreate2ros/CMakeLists.txt:76 (target_link_libraries):
  Attempt to add link library
  "/usr/lib/x86_64-linux-gnu/libboost_filesystem.so" to target "joy_node"
  which is not built in this directory.

CMake Error at irobotcreate2ros/CMakeLists.txt:76 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/libxmlrpcpp.so" to target
  "joy_node" which is not built in this directory.

CMake Error at irobotcreate2ros/CMakeLists.txt:76 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/libtf2.so" to target
  "joy_node" which is not built in this directory.

CMake Error at irobotcreate2ros/CMakeLists.txt:76 (target_link_libraries):
  Attempt to add link library
  "/opt/ros/indigo/lib/libroscpp_serialization.so" to target "joy_node" which
  is not built in this directory.

CMake Error at irobotcreate2ros/CMakeLists.txt:76 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/librosconsole.so" to
  target "joy_node" which is not built in this directory.

CMake Error at irobotcreate2ros/CMakeLists.txt:76 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/librosconsole_log4cxx.so"
  to target "joy_node" which is not built in this directory.

CMake Error at irobotcreate2ros/CMakeLists.txt:76 (target_link_libraries):
  Attempt to add link library
  "/opt/ros/indigo/lib/librosconsole_backend_interface.so" to target
  "joy_node" which is not built in this directory.

CMake Error at irobotcreate2ros/CMakeLists.txt:76 (target_link_libraries):
  Attempt to add link library "/usr/lib/liblog4cxx.so" to target "joy_node"
  which is not built in this directory.

CMake Error at irobotcreate2ros/CMakeLists.txt:76 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libboost_regex.so"
  to target "joy_node" which is not built in this directory.

CMake Error at irobotcreate2ros/CMakeLists.txt:76 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/librostime.so" to target
  "joy_node" which is not built in this directory.

CMake Error at irobotcreate2ros/CMakeLists.txt:76 (target_link_libraries):
  Attempt to add link library
  "/usr/lib/x86_64-linux-gnu/libboost_date_time.so" to target "joy_node"
  which is not built in this directory.

CMake Error at irobotcreate2ros/CMakeLists.txt:76 (target_link_libraries):
  Attempt to add link library "/opt/ros/indigo/lib/libcpp_common.so" to
  target "joy_node" which is not built in this directory.

CMake Error at irobotcreate2ros/CMakeLists.txt:76 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libboost_system.so"
  to target "joy_node" which is not built in this directory.

CMake Error at irobotcreate2ros/CMakeLists.txt:76 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libboost_thread.so"
  to target "joy_node" which is not built in this directory.

Sorry thought it wasn't working and went back to the drawing board. Now getting the following error. Please advise what I did wrong. Thank you for your help.

CMake Error at irobotcreate2ros/CMakeLists.txt:76 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libpthread.so" to
  target "joy_node" which is not built in this directory.

CMake Error at irobotcreate2ros/CMakeLists.txt:76 (target_link_libraries):
  Attempt to add link library
  "/usr/lib/x86_64-linux-gnu/libconsole_bridge.so" to target "joy_node" which
  is not built in this directory.

**Comment by MirkoFerrati** [comment]
You have multiple projects that try to create the same node "joy_node"
If you do not need our custom joystick controller, you could comment out lines:
https://github.com/MirkoFerrati/irobotcreate2ros/blob/master/CMakeLists.txt#L62
https://github.com/MirkoFerrati/irobotcreate2ros/blob/master/CMakeLists.txt#L63
https://github.com/MirkoFerrati/irobotcreate2ros/blob/master/CMakeLists.txt#L76

and use the joystick node provided by joystick_drivers.
Remember that any node publishing /cmd_vel topic will work fine.
